---
- name: Windows login kontrol
  hosts: all
  gather_facts: no
  ignore_unreachable: yes

  tasks:
    - name: WinRM login testi
      win_ping:
      register: login_result
      failed_when: false

    - name: Başarısız hostları listeye ekle
      set_fact:
        failed_hosts: "{{ failed_hosts | default([]) + [inventory_hostname] }}"
      when: login_result is failed or login_result is unreachable

    - name: Fail varsa job'ı hata ile bitir
      fail:
        msg: "Login olamayan hostlar var: {{ failed_hosts }}"
      when: failed_hosts is defined
